### ISSUE TITLE
Crash when running "displayArrayClock"

### ISSUE THREAD

**Issue by ewecan** [JosueAGtz/displayArray#1]
Crashes after running for a few minutes

**Comment by JosueAGtz** [comment]
Thanks for taking the time to report this issue, could you please indicate what code are you using or how is it crashing. 
I have seen in the past the displayArray Clock app crashing when using the library manager to download or update the bb_spi_lcd, you could try using the included version provided here.

**Comment by ewecan** [comment]
Thank you for your reply! Run "displayArrayClock.ino" in the ARDUINO folder, and after a few minutes, switching "space_Pixie" to "slash_Pixie" will get stuck

**Comment by ewecan** [comment]
I tried to comment out the following code, the program can run for a long time, but it will still get stuck
 ```
 if((secondsCounter > 25) & (secondsStatus == 0)){
            lcdDrawNumber(2,10); 
            //lcdDrawNumber(6,10); 
            secondsStatus = 1;
            secondsCounter = 0;
        } else if((secondsCounter > 25) & (secondsStatus == 1)){
            lcdDrawNumber(2,11); 
            //lcdDrawNumber(6,11); 
            secondsStatus = 0;
            secondsCounter = 0;
        }
```

**Comment by JosueAGtz** [comment]
Hi, I have now corrected those errors and the program should run normally, please copy the bb_spi_lcd folder into your Arduino libraries ( replace the existing version with the provided one).
